name: Feature Request
description: Something is missing or could be done better.
labels: ["enhancement"]
body:
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: What are you trying to do? Describe the problem, not just the solution.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: How do you think this should work? Code examples welcome.
    validations:
      required: false
