use {
    crate::types::{Idl, IdlType},
    std::fmt::Write,
};

/// Generate a Go client package from the IDL.
///
/// Uses `gagliardetto/solana-go` for Solana types (PublicKey, Instruction,
/// AccountMeta).
pub fn generate_go_client(idl: &Idl) -> String {
    let pkg_name = idl.metadata.crate_name.replace('-', "_");
    let mut out = String::new();

    // Package + imports
    writeln!(out, "// Code generated by quasar. DO NOT EDIT.").unwrap();
    writeln!(out, "package {}\n", pkg_name).unwrap();

    let has_events = !idl.events.is_empty();
    let has_args = idl.instructions.iter().any(|ix| !ix.args.is_empty());
    let has_types_with_fields = idl.types.iter().any(|t| !t.ty.fields.is_empty());
    let needs_binary = has_args || has_events || has_types_with_fields;
    let has_floats = idl.instructions.iter().any(|ix| {
        ix.args.iter().any(|a| matches!(&a.ty, IdlType::Primitive(p) if p == "f32" || p == "f64"))
    }) || idl.types.iter().any(|t| {
        t.ty.fields.iter().any(|f| matches!(&f.ty, IdlType::Primitive(p) if p == "f32" || p == "f64"))
    });

    out.push_str("import (\n");
    if needs_binary {
        out.push_str("\t\"encoding/binary\"\n");
    }
    if has_events {
        out.push_str("\t\"bytes\"\n");
    }
    if has_floats {
        out.push_str("\t\"math\"\n");
    }
    out.push('\n');
    out.push_str("\tsolana \"github.com/gagliardetto/solana-go\"\n");
    out.push_str(")\n\n");

    // Program ID
    writeln!(
        out,
        "var ProgramID = solana.MustPublicKeyFromBase58(\"{}\")\n",
        idl.address
    )
    .unwrap();

    // Discriminator variables
    for ix in &idl.instructions {
        let name = to_pascal(&ix.name);
        writeln!(
            out,
            "var {}Discriminator = [{}]byte{{{}}}",
            name,
            ix.discriminator.len(),
            format_disc(&ix.discriminator),
        )
        .unwrap();
    }
    if !idl.instructions.is_empty() {
        out.push('\n');
    }

    for acc in &idl.accounts {
        let name = to_pascal(&acc.name);
        writeln!(
            out,
            "var {}AccountDiscriminator = [{}]byte{{{}}}",
            name,
            acc.discriminator.len(),
            format_disc(&acc.discriminator),
        )
        .unwrap();
    }
    if !idl.accounts.is_empty() {
        out.push('\n');
    }

    for ev in &idl.events {
        let name = to_pascal(&ev.name);
        writeln!(
            out,
            "var {}EventDiscriminator = [{}]byte{{{}}}",
            name,
            ev.discriminator.len(),
            format_disc(&ev.discriminator),
        )
        .unwrap();
    }
    if !idl.events.is_empty() {
        out.push('\n');
    }

    // Type definitions (structs)
    for type_def in &idl.types {
        writeln!(out, "type {} struct {{", type_def.name).unwrap();
        for field in &type_def.ty.fields {
            writeln!(
                out,
                "\t{} {}",
                to_pascal(&field.name),
                go_type(&field.ty),
            )
            .unwrap();
        }
        out.push_str("}\n\n");

        // Decode function
        if !type_def.ty.fields.is_empty() {
            writeln!(
                out,
                "func Decode{}(data []byte) *{} {{",
                type_def.name, type_def.name
            )
            .unwrap();
            out.push_str("\toffset := 0\n");
            for field in &type_def.ty.fields {
                out.push_str(&decode_field_expr(
                    &to_camel(&field.name),
                    &field.ty,
                    1,
                ));
            }
            let field_assigns: Vec<String> = type_def
                .ty
                .fields
                .iter()
                .map(|f| {
                    let pascal = to_pascal(&f.name);
                    let camel = to_camel(&f.name);
                    format!("\t\t{}: {},", pascal, camel)
                })
                .collect();
            writeln!(out, "\treturn &{} {{", type_def.name).unwrap();
            for a in &field_assigns {
                writeln!(out, "{}", a).unwrap();
            }
            out.push_str("\t}\n");
            out.push_str("}\n\n");
        }
    }

    // Instruction input structs + builder functions
    for ix in &idl.instructions {
        let pascal_name = to_pascal(&ix.name);

        // Input struct
        writeln!(out, "type {}Input struct {{", pascal_name).unwrap();
        for acc in &ix.accounts {
            if acc.address.is_some() || acc.pda.is_some() {
                continue;
            }
            writeln!(out, "\t{} solana.PublicKey", to_pascal(&acc.name)).unwrap();
        }
        for arg in &ix.args {
            writeln!(
                out,
                "\t{} {}",
                to_pascal(&arg.name),
                go_type(&arg.ty),
            )
            .unwrap();
        }
        if ix.has_remaining {
            out.push_str("\tRemainingAccounts []*solana.AccountMeta\n");
        }
        out.push_str("}\n\n");

        // Builder function
        writeln!(
            out,
            "func New{}Instruction(input *{}Input) *solana.GenericInstruction {{",
            pascal_name, pascal_name,
        )
        .unwrap();

        // Accounts
        out.push_str("\taccounts := []*solana.AccountMeta{\n");
        for acc in &ix.accounts {
            let key_expr = if let Some(ref addr) = acc.address {
                format!("solana.MustPublicKeyFromBase58(\"{}\")", addr)
            } else if acc.pda.is_some() {
                let pda = acc.pda.as_ref().unwrap();
                let mut seeds = Vec::new();
                for seed in &pda.seeds {
                    match seed {
                        crate::types::IdlSeed::Const { value } => {
                            seeds.push(format!("[]byte{{{}}}", format_disc(value)));
                        }
                        crate::types::IdlSeed::Account { path } => {
                            seeds.push(format!("input.{}[:]", to_pascal(path)));
                        }
                    }
                }
                // PDA derivation inline — panic on error (invalid seeds = programmer error)
                format!(
                    "func() solana.PublicKey {{ addr, _, err := solana.FindProgramAddress([][]byte{{{}}}, ProgramID); if err != nil {{ panic(err) }}; return addr }}()",
                    seeds.join(", ")
                )
            } else {
                format!("input.{}", to_pascal(&acc.name))
            };

            let meta_expr = account_meta_expr(&key_expr, acc.signer, acc.writable);
            writeln!(out, "\t\t{},", meta_expr).unwrap();
        }
        out.push_str("\t}\n");

        if ix.has_remaining {
            out.push_str("\taccounts = append(accounts, input.RemainingAccounts...)\n");
        }

        // Data
        let disc_var = format!("{}Discriminator", pascal_name);
        if ix.args.is_empty() {
            writeln!(out, "\tdata := {}[:]", disc_var).unwrap();
        } else {
            writeln!(out, "\tdata := make([]byte, 0, 256)").unwrap();
            writeln!(out, "\tdata = append(data, {}[:]...)", disc_var).unwrap();
            for arg in &ix.args {
                out.push_str(&serialize_field_expr(&to_pascal(&arg.name), &arg.ty));
            }
        }

        out.push_str("\treturn solana.NewInstruction(ProgramID, accounts, data)\n");
        out.push_str("}\n\n");
    }

    // Event decoder
    if has_events {
        out.push_str("type DecodedEvent struct {\n");
        out.push_str("\tName string\n");
        out.push_str("\tData interface{}\n");
        out.push_str("}\n\n");

        out.push_str("func DecodeEvent(data []byte) *DecodedEvent {\n");
        for ev in &idl.events {
            let name = to_pascal(&ev.name);
            let disc_len = ev.discriminator.len();
            let type_def = idl.types.iter().find(|t| t.name == ev.name);
            writeln!(
                out,
                "\tif len(data) >= {} && bytes.Equal(data[:{}], {}EventDiscriminator[:]) {{",
                disc_len, disc_len, name,
            )
            .unwrap();
            if let Some(td) = type_def {
                if td.ty.fields.is_empty() {
                    writeln!(
                        out,
                        "\t\treturn &DecodedEvent{{Name: \"{}\", Data: nil}}",
                        ev.name
                    )
                    .unwrap();
                } else {
                    writeln!(
                        out,
                        "\t\treturn &DecodedEvent{{Name: \"{}\", Data: Decode{}(data[{}:])}}",
                        ev.name, ev.name, disc_len,
                    )
                    .unwrap();
                }
            } else {
                writeln!(
                    out,
                    "\t\treturn &DecodedEvent{{Name: \"{}\", Data: nil}}",
                    ev.name
                )
                .unwrap();
            }
            out.push_str("\t}\n");
        }
        out.push_str("\treturn nil\n");
        out.push_str("}\n\n");
    }

    out
}

/// Generate go.mod content.
pub fn generate_go_mod(module_name: &str) -> String {
    format!(
        r#"module {}

go 1.21

require github.com/gagliardetto/solana-go v1.12.0
"#,
        module_name,
    )
}

// ---------------------------------------------------------------------------
// Type mapping
// ---------------------------------------------------------------------------

fn go_type(ty: &IdlType) -> &'static str {
    match ty {
        IdlType::Primitive(p) => match p.as_str() {
            "bool" => "bool",
            "u8" => "uint8",
            "i8" => "int8",
            "u16" => "uint16",
            "i16" => "int16",
            "u32" => "uint32",
            "i32" => "int32",
            "u64" => "uint64",
            "i64" => "int64",
            "u128" => "[16]byte",
            "i128" => "[16]byte",
            "f32" => "float32",
            "f64" => "float64",
            "publicKey" => "solana.PublicKey",
            "string" => "string",
            _ => "[]byte",
        },
        IdlType::DynString { .. } => "string",
        IdlType::DynVec { .. } => "[]byte", // simplified — callers handle generics
        IdlType::Defined { .. } => "[]byte",
        IdlType::Tail { .. } => "[]byte",
    }
}

// ---------------------------------------------------------------------------
// Account meta helpers
// ---------------------------------------------------------------------------

fn account_meta_expr(key_expr: &str, signer: bool, writable: bool) -> String {
    let mut s = format!("solana.Meta({})", key_expr);
    if writable {
        s.push_str(".WRITE()");
    }
    if signer {
        s.push_str(".SIGNER()");
    }
    s
}

// ---------------------------------------------------------------------------
// Serialization
// ---------------------------------------------------------------------------

fn serialize_field_expr(name: &str, ty: &IdlType) -> String {
    match ty {
        IdlType::Primitive(p) => match p.as_str() {
            "bool" => format!(
                "\tif input.{n} {{\n\t\tdata = append(data, 1)\n\t}} else {{\n\t\tdata = append(data, 0)\n\t}}\n",
                n = name,
            ),
            "u8" => format!("\tdata = append(data, input.{})\n", name),
            "i8" => format!("\tdata = append(data, byte(input.{}))\n", name),
            "u16" => format!(
                "\t{{ var buf [2]byte; binary.LittleEndian.PutUint16(buf[:], input.{n}); data = append(data, buf[:]...) }}\n",
                n = name,
            ),
            "i16" => format!(
                "\t{{ var buf [2]byte; binary.LittleEndian.PutUint16(buf[:], uint16(input.{n})); data = append(data, buf[:]...) }}\n",
                n = name,
            ),
            "u32" => format!(
                "\t{{ var buf [4]byte; binary.LittleEndian.PutUint32(buf[:], input.{n}); data = append(data, buf[:]...) }}\n",
                n = name,
            ),
            "i32" => format!(
                "\t{{ var buf [4]byte; binary.LittleEndian.PutUint32(buf[:], uint32(input.{n})); data = append(data, buf[:]...) }}\n",
                n = name,
            ),
            "u64" => format!(
                "\t{{ var buf [8]byte; binary.LittleEndian.PutUint64(buf[:], input.{n}); data = append(data, buf[:]...) }}\n",
                n = name,
            ),
            "i64" => format!(
                "\t{{ var buf [8]byte; binary.LittleEndian.PutUint64(buf[:], uint64(input.{n})); data = append(data, buf[:]...) }}\n",
                n = name,
            ),
            "u128" | "i128" => format!(
                "\tdata = append(data, input.{}[:]...)\n",
                name,
            ),
            "f32" => format!(
                "\t{{ var buf [4]byte; binary.LittleEndian.PutUint32(buf[:], math.Float32bits(input.{n})); data = append(data, buf[:]...) }}\n",
                n = name,
            ),
            "f64" => format!(
                "\t{{ var buf [8]byte; binary.LittleEndian.PutUint64(buf[:], math.Float64bits(input.{n})); data = append(data, buf[:]...) }}\n",
                n = name,
            ),
            "publicKey" => format!(
                "\tdata = append(data, input.{}[:]...)\n",
                name,
            ),
            "string" => format!(
                "\t{{ b := []byte(input.{n}); var buf [4]byte; binary.LittleEndian.PutUint32(buf[:], uint32(len(b))); data = append(data, buf[:]...); data = append(data, b...) }}\n",
                n = name,
            ),
            _ => format!("\tdata = append(data, input.{}...)\n", name),
        },
        IdlType::DynString { .. } => format!(
            "\t{{ b := []byte(input.{n}); var buf [4]byte; binary.LittleEndian.PutUint32(buf[:], uint32(len(b))); data = append(data, buf[:]...); data = append(data, b...) }}\n",
            n = name,
        ),
        IdlType::DynVec { .. } | IdlType::Defined { .. } | IdlType::Tail { .. } => format!(
            "\tdata = append(data, input.{}...)\n",
            name,
        ),
    }
}

// ---------------------------------------------------------------------------
// Deserialization
// ---------------------------------------------------------------------------

fn decode_field_expr(name: &str, ty: &IdlType, depth: usize) -> String {
    let t = "\t".repeat(depth);
    match ty {
        IdlType::Primitive(p) => match p.as_str() {
            "bool" => format!(
                "{t}{n} := data[offset] != 0\n{t}offset += 1\n",
                t = t, n = name,
            ),
            "u8" => format!(
                "{t}{n} := data[offset]\n{t}offset += 1\n",
                t = t, n = name,
            ),
            "i8" => format!(
                "{t}{n} := int8(data[offset])\n{t}offset += 1\n",
                t = t, n = name,
            ),
            "u16" => format!(
                "{t}{n} := binary.LittleEndian.Uint16(data[offset:])\n{t}offset += 2\n",
                t = t, n = name,
            ),
            "i16" => format!(
                "{t}{n} := int16(binary.LittleEndian.Uint16(data[offset:]))\n{t}offset += 2\n",
                t = t, n = name,
            ),
            "u32" => format!(
                "{t}{n} := binary.LittleEndian.Uint32(data[offset:])\n{t}offset += 4\n",
                t = t, n = name,
            ),
            "i32" => format!(
                "{t}{n} := int32(binary.LittleEndian.Uint32(data[offset:]))\n{t}offset += 4\n",
                t = t, n = name,
            ),
            "u64" => format!(
                "{t}{n} := binary.LittleEndian.Uint64(data[offset:])\n{t}offset += 8\n",
                t = t, n = name,
            ),
            "i64" => format!(
                "{t}{n} := int64(binary.LittleEndian.Uint64(data[offset:]))\n{t}offset += 8\n",
                t = t, n = name,
            ),
            "u128" | "i128" => format!(
                "{t}var {n} [16]byte\n{t}copy({n}[:], data[offset:offset+16])\n{t}offset += 16\n",
                t = t, n = name,
            ),
            "f32" => format!(
                "{t}{n} := math.Float32frombits(binary.LittleEndian.Uint32(data[offset:]))\n{t}offset += 4\n",
                t = t, n = name,
            ),
            "f64" => format!(
                "{t}{n} := math.Float64frombits(binary.LittleEndian.Uint64(data[offset:]))\n{t}offset += 8\n",
                t = t, n = name,
            ),
            "publicKey" => format!(
                "{t}var {n} solana.PublicKey\n{t}copy({n}[:], data[offset:offset+32])\n{t}offset += 32\n",
                t = t, n = name,
            ),
            _ => format!(
                "{t}{n} := data[offset:] // unsupported type\n{t}_ = {n}\n",
                t = t, n = name,
            ),
        },
        IdlType::DynString { .. } => format!(
            "{t}{n}Len := binary.LittleEndian.Uint32(data[offset:])\n\
             {t}offset += 4\n\
             {t}{n} := string(data[offset:offset+int({n}Len)])\n\
             {t}offset += int({n}Len)\n",
            t = t, n = name,
        ),
        IdlType::DynVec { .. } | IdlType::Defined { .. } | IdlType::Tail { .. } => format!(
            "{t}{n} := data[offset:] // remaining bytes\n{t}_ = {n}\n",
            t = t, n = name,
        ),
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn format_disc(disc: &[u8]) -> String {
    disc.iter()
        .map(|b| format!("0x{:02x}", b))
        .collect::<Vec<_>>()
        .join(", ")
}

/// camelCase or snake_case → PascalCase (exported in Go)
fn to_pascal(s: &str) -> String {
    if s.contains('_') {
        s.split('_')
            .map(|word| {
                let mut chars = word.chars();
                match chars.next() {
                    None => String::new(),
                    Some(c) => c.to_uppercase().to_string() + &chars.collect::<String>(),
                }
            })
            .collect()
    } else {
        let mut chars = s.chars();
        match chars.next() {
            None => String::new(),
            Some(c) => c.to_uppercase().to_string() + &chars.collect::<String>(),
        }
    }
}

/// camelCase stays camelCase, snake_case → camelCase (unexported in Go)
fn to_camel(s: &str) -> String {
    if s.contains('_') {
        let mut first = true;
        s.split('_')
            .map(|word| {
                if first {
                    first = false;
                    word.to_string()
                } else {
                    let mut chars = word.chars();
                    match chars.next() {
                        None => String::new(),
                        Some(c) => c.to_uppercase().to_string() + &chars.collect::<String>(),
                    }
                }
            })
            .collect()
    } else {
        s.to_string()
    }
}
